version: '3'

services:

  proposta-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=proposta
      - MYSQL_USER=proposta-user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  proposta:
    image: zupacademy/proposta
    restart: on-failure
    depends_on:
      - proposta-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=proposta-mysql
      - DATABASE_USER=proposta-user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=proposta
      - DATABASE_PORT=3306
